import"./styles.css"
import { Inter } from "next/font/google"


const inter = Inter({subsets: ["latin"]});


export const metadata = {
  title: "TODO App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
      
        {children}
      </body>
    </html>
  );
}
